/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: 'hsl(var(--primary)/0.05)',
          100: 'hsl(var(--primary)/0.1)',
          200: 'hsl(var(--primary)/0.2)',
          300: 'hsl(var(--primary)/0.3)',
          400: 'hsl(var(--primary)/0.4)',
          500: 'hsl(var(--primary)/1)',
          600: 'hsl(var(--primary)/0.8)',
          700: 'hsl(var(--primary)/0.7)',
          800: 'hsl(var(--primary)/0.6)',
          900: 'hsl(var(--primary)/0.5)',
          950: 'hsl(var(--primary)/0.4)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50: 'hsl(var(--secondary)/0.05)',
          100: 'hsl(var(--secondary)/0.1)',
          200: 'hsl(var(--secondary)/0.2)',
          300: 'hsl(var(--secondary)/0.3)',
          400: 'hsl(var(--secondary)/0.4)',
          500: 'hsl(var(--secondary)/1)',
          600: 'hsl(var(--secondary)/0.8)',
          700: 'hsl(var(--secondary)/0.7)',
          800: 'hsl(var(--secondary)/0.6)',
          900: 'hsl(var(--secondary)/0.5)',
          950: 'hsl(var(--secondary)/0.4)',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
          50: 'hsl(var(--destructive)/0.05)',
          100: 'hsl(var(--destructive)/0.1)',
          200: 'hsl(var(--destructive)/0.2)',
          300: 'hsl(var(--destructive)/0.3)',
          400: 'hsl(var(--destructive)/0.4)',
          500: 'hsl(var(--destructive)/1)',
          600: 'hsl(var(--destructive)/0.8)',
          700: 'hsl(var(--destructive)/0.7)',
          800: 'hsl(var(--destructive)/0.6)',
          900: 'hsl(var(--destructive)/0.5)',
          950: 'hsl(var(--destructive)/0.4)',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
          50: 'hsl(var(--muted)/0.05)',
          100: 'hsl(var(--muted)/0.1)',
          200: 'hsl(var(--muted)/0.2)',
          300: 'hsl(var(--muted)/0.3)',
          400: 'hsl(var(--muted)/0.4)',
          500: 'hsl(var(--muted)/1)',
          600: 'hsl(var(--muted)/0.8)',
          700: 'hsl(var(--muted)/0.7)',
          800: 'hsl(var(--muted)/0.6)',
          900: 'hsl(var(--muted)/0.5)',
          950: 'hsl(var(--muted)/0.4)',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          50: 'hsl(var(--accent)/0.05)',
          100: 'hsl(var(--accent)/0.1)',
          200: 'hsl(var(--accent)/0.2)',
          300: 'hsl(var(--accent)/0.3)',
          400: 'hsl(var(--accent)/0.4)',
          500: 'hsl(var(--accent)/1)',
          600: 'hsl(var(--accent)/0.8)',
          700: 'hsl(var(--accent)/0.7)',
          800: 'hsl(var(--accent)/0.6)',
          900: 'hsl(var(--accent)/0.5)',
          950: 'hsl(var(--accent)/0.4)',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
          50: 'hsl(var(--popover)/0.05)',
          100: 'hsl(var(--popover)/0.1)',
          200: 'hsl(var(--popover)/0.2)',
          300: 'hsl(var(--popover)/0.3)',
          400: 'hsl(var(--popover)/0.4)',
          500: 'hsl(var(--popover)/1)',
          600: 'hsl(var(--popover)/0.8)',
          700: 'hsl(var(--popover)/0.7)',
          800: 'hsl(var(--popover)/0.6)',
          900: 'hsl(var(--popover)/0.5)',
          950: 'hsl(var(--popover)/0.4)',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
          50: 'hsl(var(--card)/0.05)',
          100: 'hsl(var(--card)/0.1)',
          200: 'hsl(var(--card)/0.2)',
          300: 'hsl(var(--card)/0.3)',
          400: 'hsl(var(--card)/0.4)',
          500: 'hsl(var(--card)/1)',
          600: 'hsl(var(--card)/0.8)',
          700: 'hsl(var(--card)/0.7)',
          800: 'hsl(var(--card)/0.6)',
          900: 'hsl(var(--card)/0.5)',
          950: 'hsl(var(--card)/0.4)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
